### ISSUE TITLE
Alter cases.case_citations table to fix case_citations params

### ISSUE THREAD

**Issue by tehnools** [openlawnz/openlawnz-database#3]
## Tasks
- [ ] Remove Primary Key  
- [ ] Add unique constraint for case_id  
- [ ] Add unique constraint for citation  
- [ ] Test local postgraphile API if you can query either caseCitations(citation) or  caseCitations(caseId) seperately

## Reason why it's a problem:
If you make case_id and citation a composite primary key. 

Postgraphile's resolvers will assume that to query a caseCitation you need both case_id and citation to select a single caseCitation
